### ISSUE TITLE
Update for latest release

### ISSUE THREAD

**Issue by corneliusroemer** [ComPWA/mirrors-taplo#16]
### Problem description

Please make a new release for the latest taplo update (0.9.3), this repo is at 0.8.1

### Proposed solution

NA

### Additional context

https://github.com/tamasfe/taplo/releases/tag/0.9.3

**Comment by redeboer** [comment]
See https://github.com/ComPWA/mirrors-taplo/issues/17#issuecomment-2296090823

**Comment by redeboer** [comment]
Closed by #21

**Comment by corneliusroemer** [comment]
very cool, thanks!
