### ISSUE TITLE
Current hook fails in pre-commit ci

### ISSUE THREAD

**Issue by corneliusroemer** [ComPWA/mirrors-taplo#17]
### What happened?

I added this pre-commit hook but it fails in CI (works locally):

CI: https://results.pre-commit.ci/run/github/1303538/1724027406.94fdN-hARwm4t7c9_BExrA

### Relevant log output

```
build attempt 1...
    => timeout after 120s
    [INFO] Installing environment for https://github.com/ComPWA/mirrors-taplo.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    Interrupted (^C): KeyboardInterrupt: 
    Check the log at /pc/pre-commit.log
build attempt 2...
    => timeout after 120s
    [INFO] Installing environment for https://github.com/ComPWA/mirrors-taplo.
    [INFO] Once installed this environment will be reused.
    [INFO] This may take a few minutes...
    Interrupted (^C): KeyboardInterrupt: 
    Check the log at /pc/pre-commit.log
```

### Which Python version were you using?

None

**Comment by redeboer** [comment]
Hi, thanks for your interest!
This will have to be fixed upstream. There is a PR there that addresses this, please voice your interest there to get it merged: https://github.com/tamasfe/taplo/pull/549.
